version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: smart_budget
    ports:
      - "3306:3306"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api-service:
    build:
      context: .
      dockerfile: docker/api-service.Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://mysql-db:3306/smart_budget
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - .:/app